compatibility_date = "2025-03-14"

pages_build_output_dir = "build"

name = "1link1day" 

[limits]
cpu_ms = 300_000

[[ env.development.d1_databases ]]
binding = "FEED_DB"
database_name = "FEED_DB"
database_id = "id_placeholder"

[env.production]

[env.preview]


